# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"

services:
  - MySQL
  - PostgreSQL

env:
  - TOXENV=py27-d17
  - TOXENV=py27-d18
  - TOXENV=py27-d19
  - TOXENV=py27-d110
  - TOXENV=py27-d111

  - TOXENV=py35-d18
  - TOXENV=py35-d19
  - TOXENV=py35-d110
  - TOXENV=py35-d111

before_install:
  - pip install codecov

install:
  - pip install tox "coverage<=4.0" python-coveralls>=2.5 coveralls>=0.5 codecov


script:
  - tox -e $TOXENV -- py.test tests -v --capture=no --cov=django_sysinfo --cov-config=tests/.coveragerc

after_success:
  - codecov
  - coveralls
