# Config file for automatic testing at travis-ci.org

language: python

python:
  - 3.6
  - 3.7
  - 3.8

services:
  - MySQL
  - PostgreSQL

env:
  - DJANGO=2.2
  - DJANGO=3.0
  - DJANGO=3.1


before_install:
  - pip install codecov

install:
  - pip install tox "coverage<=4.0" codecov


script:
  - tox -e "py${TRAVIS_PYTHON_VERSION//.}-d${DJANGO//.}"

before_success:
  - coverage erase

after_success:
  - coverage combine
  - codecov
